import Head from "next/head";
import Navbar from "./navbar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/pokeball.png" />
      </Head>
      <Navbar />
      <main className="bg-slate-100 p-5 min-h-screen font-sans pb-16">
        {children}
      </main>
    </>
  );
}
