import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "./components/Card";
import Navbar from "./components/Navbar";

export default function HomePage({ pokemons }) {
  const [loading, setLoading] = useState(false);
  const [count, setCount] = useState(40);

  //récupération des 40 premiers pokemons
  const firstPokemons = pokemons.slice(0, count);

  //scroll load avec délais pour test
  useEffect(() => {
    if (loading === true) {
      setTimeout(() => {
        setCount(count + 20);
        setLoading(false);
      }, "1000");
    }
    window.addEventListener("scroll", loadMore);
    return () => window.removeEventListener("scroll", loadMore);
  }, [count, loading]);

  const loadMore = () => {
    if (
      window.innerHeight + document.documentElement.scrollTop + 1 >
      document.scrollingElement.scrollHeight
    ) {
      setLoading(true);
    }
  };

  // console.log(pokemons);

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/pokeball.png" />
      </Head>
      <Navbar />
      <div className="bg-slate-100 w-screen min-h-screen flex flex-wrap justify-center p-4 relative">
        {loading && (
          <div role="status" className="absolute bottom-0 right-0 m-4">
            <img className="w-20" src="./images/DD0.gif" alt="Carapuce bg" />
          </div>
        )}

        {firstPokemons &&
          firstPokemons.map((pokemon, id) => (
            <Card pokemon={pokemon} key={pokemon.id} />
          ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://pokebuildapi.fr/api/v1/pokemon");
  const pokemons = await res.json();

  return {
    props: {
      pokemons,
    },
  };
}
